name: ec2-creation
on: [push] # triggers
jobs: 
  # Job1 and Job4 are parellel. No dependency
  terraform: # these should be unique
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init

      
      - name: run plan
        run: terraform plan
