name: ec2-creation
on: [push] # triggers
jobs: 
  # Job1 and Job4 are parellel. No dependency
  terraform: # these should be unique
    runs-on: ubuntu-latest # Linux OS. We can have windows or MAC
    steps: # stages
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
      
      - name: run plan
        run: terraform plan
